services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    command: yarn start:dev
    # 🔴 REMOVE this to avoid overwriting container content
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../bjm-admin/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf