services:
  backend:
    build:
      context: ./bjm-backend
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"
    volumes:
      - ./bjm-backend:/app
    command: yarn start:dev

  nginx:
    build:
      context: ./bjm-backend
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./bjm-admin/dist:/usr/share/nginx/html
