

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"
    volumes:
      - .:/app
    command: yarn start:dev

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../bjm-admin/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
